Bug with categories fixed. Bug with parsing fields "images" and "anno…
somal/VIA2COCO pull request #2
Opened 2021-10-07 07:52 UTC by Tpoc311

Bug with categories fixed. Bug with parsing fields "images" and "annotations" fixed. Code refactored.

2021-10-07 11:33 UTC, somal requested changes

2021-10-07 11:33 UTC, somal commented on convert.py
> +def get_all_categories(rows: list) -> (list, set):
Можешь добавить док-стринги для методов, чтобы везде были?
И соответственно типы из модуля typing

2021-10-07 11:33 UTC, somal commented on convert.py
> +        #
```suggestion
```

2021-10-08 14:06 UTC, Tpoc311 commented on convert.py
> +        #
Исправил перед коммитом

2021-10-08 14:06 UTC, Tpoc311 commented on convert.py
> +def get_all_categories(rows: list) -> (list, set):
Добавил docstrings и типы данных из библиотеки typing

2021-10-11 13:44 UTC, somal approved these changes

2021-10-11 13:44 UTC, merged